spring:
  application:
    name: movies
  datasource:
    url: jdbc:postgresql://localhost:5432/movies
    username: movies
    password: movies
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 8080