spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movies
    username: movies
    password: movies
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: public
  flyway:
    locations: classpath:db/migration
server:
  port: 8080