services:
  db:
    image: postgres:16
    container_name: movies_db
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: movies
      POSTGRES_PASSWORD: movies
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movies -d movies"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: movies_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data: