services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: movies
      POSTGRES_PASSWORD: movies
    ports: ["5432:5432"]
    volumes: ["db_data:/var/lib/postgresql/data"]
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
volumes:
  db_data: